#ifndef LM_CONNECTORTYPE_H
#define LM_CONNECTORTYPE_H

#include "qstring.h"

enum lmConnectorType
{
	LM_CONNECTOR_UNKNOWN,
	LM_CONNECTOR_STUD,
	LM_CONNECTOR_STUD_INLET,
	LM_CONNECTOR_AXLE,
	LM_CONNECTOR_AXLE_HOLE,
	LM_CONNECTOR_CYLINDRICAL,
	LM_CONNECTOR_CYLINDRICAL_HOLE
};

#endif // LM_CONNECTORTYPE_H
